# -*- coding: utf-8 -*-
"""human.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F59qs2eVsm82f2Wxv7BhtvabA_-MLvtZ
"""

class Human:
  leg_number = 2
  def walk():
    print('Walk 1 step')